# Generated by Django 4.2.16 on 2026-05-24 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='bmilog',
            new_name='tracker_bmi_user_id_2dcf65_idx',
            old_name='tracker_bmi_user_id_8f5b7c_idx',
        ),
        migrations.RenameIndex(
            model_name='workoutlog',
            new_name='tracker_wor_user_id_8e4a26_idx',
            old_name='tracker_wor_user_id_c93b4b_idx',
        ),
    ]
