# Generated by Django 4.2.16 on 2026-05-24 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='meallog',
            new_name='nutrition_m_user_id_62bcf7_idx',
            old_name='nutrition_m_user_id_67cf95_idx',
        ),
    ]
