# Generated by Django 4.2.16 on 2026-06-15 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_rename_nutrition_m_user_id_67cf95_idx_nutrition_m_user_id_62bcf7_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietprofile',
            name='carbs_g',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='dietprofile',
            name='daily_calories_target',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dietprofile',
            name='fats_g',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='dietprofile',
            name='protein_g',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='meallog',
            name='carbs_g',
            field=models.DecimalField(decimal_places=1, max_digits=6),
        ),
        migrations.AlterField(
            model_name='meallog',
            name='fats_g',
            field=models.DecimalField(decimal_places=1, max_digits=6),
        ),
        migrations.AlterField(
            model_name='meallog',
            name='protein_g',
            field=models.DecimalField(decimal_places=1, max_digits=6),
        ),
    ]
