# Generated by Django 4.2.16 on 2026-06-15 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedplan',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='generatedplan',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('done', 'Done'), ('failed', 'Failed')], db_index=True, default='pending', max_length=12),
        ),
        migrations.AlterField(
            model_name='generatedplan',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='generatedplan',
            name='plan_content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='generatedplan',
            name='user_inputs',
            field=models.JSONField(default=dict),
        ),
        migrations.AddIndex(
            model_name='generatedplan',
            index=models.Index(fields=['user', '-generated_at'], name='ai_planner__user_id_379247_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedplan',
            index=models.Index(fields=['user', 'is_active'], name='ai_planner__user_id_33ebcd_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedplan',
            index=models.Index(fields=['user', 'status'], name='ai_planner__user_id_303296_idx'),
        ),
    ]
