apiVersion: v1
kind: Namespace
metadata:
  name: fitforge
  labels:
    app.kubernetes.io/name: fitforge
    app.kubernetes.io/part-of: fitforge
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
