apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fitforge-staging

resources:
  - ../../base

namePrefix: stg-

images:
  - name: fitforge
    newName: registry.fitforge.app/fitforge
    newTag: staging

patches:
  - target:
      kind: Deployment
      name: fitforge-web
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: Ingress
      name: fitforge
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: staging.fitforge.app
      - op: replace
        path: /spec/tls/0/hosts/0
        value: staging.fitforge.app
      - op: replace
        path: /spec/tls/0/secretName
        value: fitforge-staging-tls
  - target:
      kind: ConfigMap
      name: fitforge-config
    patch: |
      - op: replace
        path: /data/SENTRY_ENVIRONMENT
        value: staging
      - op: replace
        path: /data/LOG_LEVEL
        value: INFO
      - op: replace
        path: /data/DEBUG
        value: "False"
